# Generated by Django 4.0.4 on 2022-06-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_students_extra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='extra_data',
        ),
    ]
